#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM ubuntu:18.04

ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/
ENV PATH=$PATH:/opt/apache-maven-3.6.3/bin

RUN pwd ; uname -a && \
    apt-get update -y && \
    apt-get install build-essential -y && \
    apt-get install software-properties-common -y && \
    apt-get update -y  && \
    sudo add-apt-repository ppa:openjdk-r/ppa -y && \
    apt-get update -y && \
    apt-get install openjdk-8-jdk -y && \
    apt-get install g++-mingw-w64 -y && \
    apt-get install gcc-multilib -y && \
    apt-get install libssl-dev -y && \
    ln -s /usr/include/x86_64-linux-gnu /usr/include/i386-linux-gnu && \
    ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h && \
    apt-get install git -y && \
    apt-get install wget -y && \
    cd ~ && \
    wget https://dlcdn.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
    cd /opt && \
    tar -zxf ~/apache-maven-3.6.3-bin.tar.gz && \
    sudo dpkg --purge --force-depends ca-certificates-java && \
    apt-get install ca-certificates-java -y && \
    apt-get install g++-multilib -y && \
    export OPENSSL_HOME=/usr && \
    cd ~


CMD /bin/bash
