# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI Win

# This is a temporary workflow for use in debugging the Windows build
# At present it fails to find the header file openssl/aes.h
# Not clear yet if that is missing or in an unexpected place.

on:
  workflow_dispatch:
  # trigger outselves on change
  push:
    paths:
      - '**/workflows/maven_win.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # Trying to fix Windows build
        os: [windows-latest]
        java: [ 8 ]
        experimental: [false]
      fail-fast: false
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.0.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: OpenSSL version
      run: openssl version
    # - name: Find missing file
    #   run: |
    #     c:
    #     cd \
    #     dir
    #     ruby -rfind -e "Find.find('.').each{|x| puts x if x.include? 'openssl'}"
    #     d:
    #     cd \
    #     dir
    #     ruby -rfind -e "Find.find('.').each{|x| puts x if x.include? 'openssl'}"
    #     set
    - name: Build with Maven
      run: |
        env
        set OPENSSL_HOME "C:\Miniconda\pkgs\openssl-1.1.1n-h2bbff1b_0\Library"
        mvn -V --file pom.xml --no-transfer-progress -DtrimStackTrace=false
